project:
  type: website
  output-dir: docs

website:
  title: "Data Diary"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hadi-gharibi
      - icon: twitter
        href: https://twitter.com/GharibiHadi
format:
  html:
    theme: cosmo
    css: styles.css



